
scrape_configs:
  - job_name: otel-demo
    scrape_interval: 10s
    dns_sd_configs:
      - names:
        - otel-app
        type: 'A'
        port: 80
      - names:
        - otel-proxy-app
        type: 'A'
        port: 81